services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "pgrep", "nginx"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  docker: null
